### ISSUE TITLE
Ore Spawning Issues

### ISSUE THREAD

**Issue by jsaggers** [Zairus/IskalliumReactors#1]
It doesn't matter what I set the config to it makes no difference in game, I tried many different variations with no luck
Created a test pack with:
1. Iskallium Reactors
2. JEI
3. COFH (because your mod crashes without there API installed or some form of it)
4. World Stripper

Currently it generates maybe one ore every 4x4 chunk area, no matter what the config file is set to.

**Comment by WinterGrave** [comment]
I have tested this and ore does generate more often if you lower the rarity value. Will do more tests to check this.

**Comment by nenomius** [comment]
As I see in code, [config](https://github.com/Zairus/IskalliumReactors/blob/8c2f631ae68876f163c125db53f6d185bb687124/src/main/java/zairus/iskalliumreactors/IRConfig.java) has two values responsible for iskallium ore generation: iskalliumGenerationWeight and iskalliumGenerationPatchSize.

[The only place iskalliumGenerationWeight is used](https://github.com/Zairus/IskalliumReactors/blob/8c2f631ae68876f163c125db53f6d185bb687124/src/main/java/zairus/iskalliumreactors/IskalliumReactors.java#L57) is a second parameter for [net.minecraftforge.fml.common.registry.GameRegistry.registerWorldGenerator](https://github.com/MinecraftForge/MinecraftForge/blob/c8d775c865bc6fba204072c2ac18cd64d787112f/src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java#L82) method. Javadoc on which says 
> modGenerationWeight a weight to assign to this generator. Heavy weights tend to sink to the bottom of list of world generators (i.e. they run later)

i.e. it does not influence rarity *directly*, but can do it *indirectly* if other generators use all the stone for other ores. I did couple of tests and looked with mcedit, it really does not make any significant difference (something like changing roughly 1 ore per 10 chunks to 1 per 9 chunks).

iskalliumGenerationPatchSize is used [here](https://github.com/Zairus/IskalliumReactors/blob/8c2f631ae68876f163c125db53f6d185bb687124/src/main/java/zairus/iskalliumreactors/world/gen/feature/WorldGenIskalliumOre.java) to calculate value of `size` which is … never used.

Either I did miss something or config does not influence iskallium ore generation.

**Comment by wleroux** [comment]
@nenomius Zarius has recently approved a code review that makes use of the iskalliumGenerationPatchSize, so it should now work.

**Comment by WinterGrave** [comment]
This was fixed thanks to @wleroux
