### ISSUE TITLE
Crash with Mekanism

### ISSUE THREAD

**Issue by tigerdan2** [Zairus/IskalliumReactors#13]
Pretty straightup crashreport

http://prntscr.com/i88j56
i placed a advanced energycell from mekanism next to my reactor output aaannd it crashed
https://hastebin.com/afapapupiv.css

Extra information
SP
1.12.2
Running iskalliumreactors-1.12.2-0.5.14

**Comment by WinterGrave** [comment]
Has been fixed

**Comment by Sinmiru** [comment]
Had a crash after placing an Ultimate Cable from Mekanism on the power port, unsure if this is the same problem but I'll put this here in case it helps. If the fix just hasn't been posted to curse, feel free to ignore this. Thanks.
[crash-2019-03-09_23.38.18-server.txt](https://github.com/Zairus/IskalliumReactors/files/2949150/crash-2019-03-09_23.38.18-server.txt)
