### ISSUE TITLE
Low throughput

### ISSUE THREAD

**Issue by Fortist** [Zairus/IskalliumReactors#17]
Giving it anything that can handle the thousands of rf it has in the powertap doesnt make it any faster, AND it doesnt even empty whats in the powertap.

Man, I had high hopes for this mod, spent far too much time fixing it. Maybe this'll update at some point.

**Comment by WinterGrave** [comment]
Hi there, how many iskallium blocks do you have in the reactor? The power tap never empties it will provide constants 160 RF/T per each iskallium block inside, no more than that

**Comment by WinterGrave** [comment]
Closing for no response
