### ISSUE TITLE
Controller creates lag

### ISSUE THREAD

**Issue by danieldebuhr** [Zairus/IskalliumReactors#2]
As soon as i place the controller in the world - while the reactor is not finished in his structure - the game starts to lag heavily. As the structure is finished, the lag disappears. 
If i then break the reactor to attach more iskallium, the lag comes back until i finish the structure.
While the structure is like its supposed to be, everything works fine.

I have no other lag issues with this modpack and it only occours under the mentioned circumstances. So i think it has something to do with the check-routine of the controller.

**Comment by TheonlyTazz** [comment]
Can confirm, we had this issue just earlier today

Breaking the controller imidiatly stopped the lag.
It seems the controller is looking for the complete structure or so

Regards 
Tazz

**Comment by WinterGrave** [comment]
Fixed in latest version

**Comment by TheonlyTazz** [comment]
is this already on the 1.2.1 version of foolcraft?
