### ISSUE TITLE
Power Tap Continues Providing Power When Reactor is Destroyed

### ISSUE THREAD

**Issue by imrgr** [Zairus/IskalliumReactors#3]
![2017-03-24_15 24 59](https://cloud.githubusercontent.com/assets/26236636/24315760/498fb586-10a6-11e7-95f8-127de5d34b13.png)

**Comment by imrgr** [comment]
And no, it wasn't from RF left over in the conduit.

**Comment by imrgr** [comment]
I did some more messing around with this, and it only occurs if the Controller is the first block that you break. For instance, if you break a Steel Block first, then the Power Tap will stop producing RF. If you break the Controller first, then the Power Tap will keep going and you will then be able to break the rest of the reactor.

**Comment by WinterGrave** [comment]
Could confirm ans just fixed it, publishing the update. Thank you very much.
