### ISSUE TITLE
Where is this stuff!?

### ISSUE THREAD

**Issue by Gerdathlete** [Zairus/IskalliumReactors#4]
I find iskallium almost impossible to find, and I'm wondering if there is a certain height that it spawns most frequently at. My current strategy is just leveling entire chunks.

**Comment by Gerdathlete** [comment]
Every ore I've found is around diamond level... Should I stick around there?

**Comment by imrgr** [comment]
It is supposed to be rare, but the rarity is configurable. Why don't you close this and stop wasting the developers time. This is supposed to be for real bugs.

**Comment by WinterGrave** [comment]
This changed on the latest version, it now generates correctly
