### ISSUE TITLE
Ore spawning for Deep Dark and ExtraUtils2 mining dimension

### ISSUE THREAD

**Issue by miksbricks** [Zairus/IskalliumReactors#6]
Can you add ore gen rules for those two so Iskallium can be obtained via one of those methods?

**Comment by WinterGrave** [comment]
I have it on the list

**Comment by wleroux** [comment]
I've created a pull request #9 that fixes this issue. Waiting for Zarius to approve. :) Cheers!

**Comment by WinterGrave** [comment]
I have implemented the changes in 1.12.2 didn't merge pull request because had other changes too
